framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
    cache:
        prefix_seed: symfony-official-gendarmerie-reduction
