twig:
    default_path: '%kernel.project_dir%/templates'
    exception_controller: null
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        # To easily loop supported locales and show alternative links (I18N links for an Twig extension)
        app_locales: '%app_locales%'
    # Email templates using these paths
    paths:
        '%kernel.project_dir%/public/assets/images': images
        '%kernel.project_dir%/public/assets/css': css
