parameters:
    locale: 'fr'
    faker_locale: 'fr_FR'
    app_locales: fr|en

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.earth:
        class: Innmind\TimeContinuum\TimeContinuum\Earth
    app.format:
        class: Innmind\TimeContinuum\Format\ISO8601

    App\Service\GlobalClock:
        arguments:
            $clock: '@app.earth'
            $format: '@app.format'