parameters:
    locale: 'fr'
    faker_locale: 'fr_FR'
    app_locales: fr|en

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $httpClient: '@app.client'

    app.client:
        class: GuzzleHttp\Client
    app.earth:
        class: Innmind\TimeContinuum\TimeContinuum\Earth
    app.format:
        class: Innmind\TimeContinuum\Format\ISO8601

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\GlobalClock:
        arguments:
            $clock: '@app.earth'
            $format: '@app.format'
